#! /bin/bash

#Validamos que existan 2 argumentos
if [ "$#" -ne 2 ]
then
  echo 'Error, debe indicar el grupo de acceso y el correo del usuario'
  exit 1

else
  accessgroup=$1
  user=$2

  id=$(sh get-id.sh $user) 
  echo "Actualizando permisos"
  case $accessgroup in

  Test-Backups)
    ibmcloud sl user permission-edit $id --permission "HARDWARE_VIEW" 
    ibmcloud sl user permission-edit $id --permission "NAS_MANAGE" 
    ibmcloud sl user permission-edit $id --permission "VIRTUAL_GUEST_VIEW" 

    ibmcloud sl user permission-edit $id --permission "ACCESS_ALL_GUEST" 
    ibmcloud sl user permission-edit $id --permission "ACCESS_ALL_HARDWARE" 

    ibmcloud sl user permission-edit $id --permission "TICKET_ADD" 
    ibmcloud sl user permission-edit $id --permission "TICKET_EDIT" 
    ibmcloud sl user permission-edit $id --permission "TICKET_MANAGE" 
    ibmcloud sl user permission-edit $id --permission "TICKET_SEARCH" 
    ibmcloud sl user permission-edit $id --permission "TICKET_VIEW" 
    ibmcloud sl user permission-edit $id --permission "TICKET_VIEW_ALL" 
    ibmcloud sl user permission-edit $id --permission "TICKET_VIEW_BY_HARDWARE" 
    ibmcloud sl user permission-edit $id --permission "TICKET_VIEW_BY_VIRTUAL_GUEST" 	   
    ;;

  Test-Networking)
    ibmcloud sl user permission-edit $id --permission "BANDWIDTH_MANAGE" 
    ibmcloud sl user permission-edit $id --permission "CDN_ACCOUNT_MANAGE" 
    ibmcloud sl user permission-edit $id --permission "CDN_BANDWIDTH_VIEW" 
    ibmcloud sl user permission-edit $id --permission "CDN_FILE_MANAGE" 
    ibmcloud sl user permission-edit $id --permission "FIREWALL_MANAGE" 
    ibmcloud sl user permission-edit $id --permission "GATEWAY_MANAGE" 
    ibmcloud sl user permission-edit $id --permission "HARDWARE_VIEW" 
    ibmcloud sl user permission-edit $id --permission "IP_ADD" 
    ibmcloud sl user permission-edit $id --permission "NETWORK_ROUTE_MANAGE" 
    ibmcloud sl user permission-edit $id --permission "VIRTUAL_GUEST_VIEW" 


    ibmcloud sl user permission-edit $id --permission "ACCESS_ALL_GUEST" 
    ibmcloud sl user permission-edit $id --permission "ACCESS_ALL_HARDWARE" 

    ibmcloud sl user permission-edit $id --permission "TICKET_ADD" 
    ibmcloud sl user permission-edit $id --permission "TICKET_EDIT" 
    ibmcloud sl user permission-edit $id --permission "TICKET_MANAGE" 
    ibmcloud sl user permission-edit $id --permission "TICKET_SEARCH" 
    ibmcloud sl user permission-edit $id --permission "TICKET_VIEW" 
    ibmcloud sl user permission-edit $id --permission "TICKET_VIEW_ALL" 
    ibmcloud sl user permission-edit $id --permission "TICKET_VIEW_BY_HARDWARE" 
    ibmcloud sl user permission-edit $id --permission "TICKET_VIEW_BY_VIRTUAL_GUEST"  
    ;;

  Test-Platform)
    ibmcloud sl user permission-edit $id --permission "ADD_SERVICE_STORAGE"  
    ibmcloud sl user permission-edit $id --permission "ANTI_MALWARE_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "BANDWIDTH_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "CDN_ACCOUNT_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "CDN_BANDWIDTH_VIEW"  
    ibmcloud sl user permission-edit $id --permission "CDN_FILE_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "CUSTOMER_POST_PROVISION_SCRIPT_MANAGEMENT"  
    ibmcloud sl user permission-edit $id --permission "CUSTOMER_SSH_KEY_MANAGEMENT"  
    ibmcloud sl user permission-edit $id --permission "DATACENTER_ACCESS"  
    ibmcloud sl user permission-edit $id --permission "DATACENTER_ROOM_ACCESS"  
    ibmcloud sl user permission-edit $id --permission "DEDICATED_HOST_VIEW"  
    ibmcloud sl user permission-edit $id --permission "DNS_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "FIREWALL_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "FIREWALL_RULE_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "GATEWAY_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "HARDWARE_VIEW"  
    ibmcloud sl user permission-edit $id --permission "HOSTNAME_EDIT"  
    ibmcloud sl user permission-edit $id --permission "HOST_ID_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "INSTANCE_UPGRADE"  
    ibmcloud sl user permission-edit $id --permission "IP_ADD"  
    ibmcloud sl user permission-edit $id --permission "LICENSE_VIEW"  
    ibmcloud sl user permission-edit $id --permission "LOADBALANCER_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "LOCKBOX_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "MANAGE_SECURITY_GROUPS"  
    ibmcloud sl user permission-edit $id --permission "MONITORING_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "NAS_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "NETWORK_MESSAGE_DELIVERY_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "NETWORK_ROUTE_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "NETWORK_TUNNEL_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "NETWORK_VLAN_SPANNING"  
    ibmcloud sl user permission-edit $id --permission "NTF_SUBSCRIBER_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "PORT_CONTROL"  
    ibmcloud sl user permission-edit $id --permission "PUBLIC_IMAGE_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "PUBLIC_NETWORK_COMPUTE"  
    ibmcloud sl user permission-edit $id --permission "REMOTE_MANAGEMENT"  
    ibmcloud sl user permission-edit $id --permission "SAML_AUTHENTICATION_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "SCALE_GROUP_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "SECURITY_CERTIFICATE_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "SECURITY_CERTIFICATE_VIEW"  
    ibmcloud sl user permission-edit $id --permission "SERVER_ADD"  
    ibmcloud sl user permission-edit $id --permission "SERVER_CANCEL"  
    ibmcloud sl user permission-edit $id --permission "SERVER_RELOAD"  
    ibmcloud sl user permission-edit $id --permission "SERVER_UPGRADE"  
    ibmcloud sl user permission-edit $id --permission "SERVICE_ADD"  
    ibmcloud sl user permission-edit $id --permission "SERVICE_CANCEL"  
    ibmcloud sl user permission-edit $id --permission "SERVICE_UPGRADE"  
    ibmcloud sl user permission-edit $id --permission "SOFTWARE_FIREWALL_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "USER_EVENT_LOG_VIEW"  
    ibmcloud sl user permission-edit $id --permission "USER_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "VIEW_CPANEL"  
    ibmcloud sl user permission-edit $id --permission "VIEW_CUSTOMER_SOFTWARE_PASSWORD"  
    ibmcloud sl user permission-edit $id --permission "VIEW_HELM"  
    ibmcloud sl user permission-edit $id --permission "VIEW_PLESK"  
    ibmcloud sl user permission-edit $id --permission "VIEW_QUANTASTOR"  
    ibmcloud sl user permission-edit $id --permission "VIEW_URCHIN"  
    ibmcloud sl user permission-edit $id --permission "VIRTUAL_GUEST_VIEW"  
    ibmcloud sl user permission-edit $id --permission "VPN_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "VULN_SCAN_MANAGE"  

    ibmcloud sl user permission-edit $id --permission "ACCESS_ALL_GUEST"  
    ibmcloud sl user permission-edit $id --permission "ACCESS_ALL_HARDWARE"  

    ibmcloud sl user permission-edit $id --permission "TICKET_ADD"  
    ibmcloud sl user permission-edit $id --permission "TICKET_EDIT"  
    ibmcloud sl user permission-edit $id --permission "TICKET_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "TICKET_SEARCH"  
    ibmcloud sl user permission-edit $id --permission "TICKET_VIEW"  
    ibmcloud sl user permission-edit $id --permission "TICKET_VIEW_ALL"  
    ibmcloud sl user permission-edit $id --permission "TICKET_VIEW_BY_HARDWARE"  
    ibmcloud sl user permission-edit $id --permission "TICKET_VIEW_BY_VIRTUAL_GUEST" 
    ;;

  Test-IAM)
    ibmcloud sl user permission-edit $id --permission "ADD_SERVICE_STORAGE"  
    ibmcloud sl user permission-edit $id --permission "ANTI_MALWARE_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "BANDWIDTH_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "CDN_ACCOUNT_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "CDN_BANDWIDTH_VIEW"  
    ibmcloud sl user permission-edit $id --permission "CDN_FILE_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "CUSTOMER_POST_PROVISION_SCRIPT_MANAGEMENT"  
    ibmcloud sl user permission-edit $id --permission "CUSTOMER_SSH_KEY_MANAGEMENT"  
    ibmcloud sl user permission-edit $id --permission "DATACENTER_ACCESS"  
    ibmcloud sl user permission-edit $id --permission "DATACENTER_ROOM_ACCESS"  
    ibmcloud sl user permission-edit $id --permission "DEDICATED_HOST_VIEW"  
    ibmcloud sl user permission-edit $id --permission "DNS_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "FIREWALL_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "FIREWALL_RULE_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "GATEWAY_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "HARDWARE_VIEW"  
    ibmcloud sl user permission-edit $id --permission "HOSTNAME_EDIT"  
    ibmcloud sl user permission-edit $id --permission "HOST_ID_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "INSTANCE_UPGRADE"  
    ibmcloud sl user permission-edit $id --permission "IP_ADD"  
    ibmcloud sl user permission-edit $id --permission "LICENSE_VIEW"  
    ibmcloud sl user permission-edit $id --permission "LOADBALANCER_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "LOCKBOX_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "MANAGE_SECURITY_GROUPS"  
    ibmcloud sl user permission-edit $id --permission "MONITORING_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "NAS_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "NETWORK_MESSAGE_DELIVERY_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "NETWORK_ROUTE_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "NETWORK_TUNNEL_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "NETWORK_VLAN_SPANNING"  
    ibmcloud sl user permission-edit $id --permission "NTF_SUBSCRIBER_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "PORT_CONTROL"  
    ibmcloud sl user permission-edit $id --permission "PUBLIC_IMAGE_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "PUBLIC_NETWORK_COMPUTE"  
    ibmcloud sl user permission-edit $id --permission "REMOTE_MANAGEMENT"  
    ibmcloud sl user permission-edit $id --permission "SAML_AUTHENTICATION_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "SCALE_GROUP_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "SECURITY_CERTIFICATE_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "SECURITY_CERTIFICATE_VIEW"  
    ibmcloud sl user permission-edit $id --permission "SERVER_ADD"  
    ibmcloud sl user permission-edit $id --permission "SERVER_CANCEL"  
    ibmcloud sl user permission-edit $id --permission "SERVER_RELOAD"  
    ibmcloud sl user permission-edit $id --permission "SERVER_UPGRADE"  
    ibmcloud sl user permission-edit $id --permission "SERVICE_ADD"  
    ibmcloud sl user permission-edit $id --permission "SERVICE_CANCEL"  
    ibmcloud sl user permission-edit $id --permission "SERVICE_UPGRADE"  
    ibmcloud sl user permission-edit $id --permission "SOFTWARE_FIREWALL_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "USER_EVENT_LOG_VIEW"  
    ibmcloud sl user permission-edit $id --permission "USER_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "VIEW_CPANEL"  
    ibmcloud sl user permission-edit $id --permission "VIEW_CUSTOMER_SOFTWARE_PASSWORD"  
    ibmcloud sl user permission-edit $id --permission "VIEW_HELM"  
    ibmcloud sl user permission-edit $id --permission "VIEW_PLESK"  
    ibmcloud sl user permission-edit $id --permission "VIEW_QUANTASTOR"  
    ibmcloud sl user permission-edit $id --permission "VIEW_URCHIN"  
    ibmcloud sl user permission-edit $id --permission "VIRTUAL_GUEST_VIEW"  
    ibmcloud sl user permission-edit $id --permission "VPN_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "VULN_SCAN_MANAGE"  

    ibmcloud sl user permission-edit $id --permission "ACCESS_ALL_GUEST"  	
    ibmcloud sl user permission-edit $id --permission "ACCESS_ALL_HARDWARE"  

    ibmcloud sl user permission-edit $id --permission "TICKET_ADD"  
    ibmcloud sl user permission-edit $id --permission "TICKET_EDIT"  
    ibmcloud sl user permission-edit $id --permission "TICKET_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "TICKET_SEARCH"  
    ibmcloud sl user permission-edit $id --permission "TICKET_VIEW"  
    ibmcloud sl user permission-edit $id --permission "TICKET_VIEW_ALL"  
    ibmcloud sl user permission-edit $id --permission "TICKET_VIEW_BY_HARDWARE"  
    ibmcloud sl user permission-edit $id --permission "TICKET_VIEW_BY_VIRTUAL_GUEST" 
    ;;

  Test-Cloud)
    ibmcloud sl user permission-edit $id --permission "ADD_SERVICE_STORAGE"  
    ibmcloud sl user permission-edit $id --permission "ANTI_MALWARE_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "BANDWIDTH_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "CDN_ACCOUNT_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "CDN_BANDWIDTH_VIEW"  
    ibmcloud sl user permission-edit $id --permission "CDN_FILE_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "CUSTOMER_POST_PROVISION_SCRIPT_MANAGEMENT"  
    ibmcloud sl user permission-edit $id --permission "CUSTOMER_SSH_KEY_MANAGEMENT"  
    ibmcloud sl user permission-edit $id --permission "DATACENTER_ACCESS"  
    ibmcloud sl user permission-edit $id --permission "DATACENTER_ROOM_ACCESS"  
    ibmcloud sl user permission-edit $id --permission "DEDICATED_HOST_VIEW"  
    ibmcloud sl user permission-edit $id --permission "DNS_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "FIREWALL_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "FIREWALL_RULE_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "GATEWAY_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "HARDWARE_VIEW"  
    ibmcloud sl user permission-edit $id --permission "HOSTNAME_EDIT"  
    ibmcloud sl user permission-edit $id --permission "HOST_ID_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "INSTANCE_UPGRADE"  
    ibmcloud sl user permission-edit $id --permission "IP_ADD"  
    ibmcloud sl user permission-edit $id --permission "LICENSE_VIEW"  
    ibmcloud sl user permission-edit $id --permission "LOADBALANCER_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "LOCKBOX_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "MANAGE_SECURITY_GROUPS"  
    ibmcloud sl user permission-edit $id --permission "MONITORING_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "NAS_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "NETWORK_MESSAGE_DELIVERY_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "NETWORK_ROUTE_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "NETWORK_TUNNEL_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "NETWORK_VLAN_SPANNING"  
    ibmcloud sl user permission-edit $id --permission "NTF_SUBSCRIBER_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "PORT_CONTROL"  
    ibmcloud sl user permission-edit $id --permission "PUBLIC_IMAGE_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "PUBLIC_NETWORK_COMPUTE"  
    ibmcloud sl user permission-edit $id --permission "REMOTE_MANAGEMENT"  
    ibmcloud sl user permission-edit $id --permission "SAML_AUTHENTICATION_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "SCALE_GROUP_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "SECURITY_CERTIFICATE_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "SECURITY_CERTIFICATE_VIEW"  
    ibmcloud sl user permission-edit $id --permission "SERVER_ADD"  
    ibmcloud sl user permission-edit $id --permission "SERVER_CANCEL"  
    ibmcloud sl user permission-edit $id --permission "SERVER_RELOAD"  
    ibmcloud sl user permission-edit $id --permission "SERVER_UPGRADE"  
    ibmcloud sl user permission-edit $id --permission "SERVICE_ADD"  
    ibmcloud sl user permission-edit $id --permission "SERVICE_CANCEL"  
    ibmcloud sl user permission-edit $id --permission "SERVICE_UPGRADE"  
    ibmcloud sl user permission-edit $id --permission "SOFTWARE_FIREWALL_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "USER_EVENT_LOG_VIEW"  
    ibmcloud sl user permission-edit $id --permission "USER_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "VIEW_CPANEL"  
    ibmcloud sl user permission-edit $id --permission "VIEW_CUSTOMER_SOFTWARE_PASSWORD"  
    ibmcloud sl user permission-edit $id --permission "VIEW_HELM"  
    ibmcloud sl user permission-edit $id --permission "VIEW_PLESK"  
    ibmcloud sl user permission-edit $id --permission "VIEW_QUANTASTOR"  
    ibmcloud sl user permission-edit $id --permission "VIEW_URCHIN"  
    ibmcloud sl user permission-edit $id --permission "VIRTUAL_GUEST_VIEW"  
    ibmcloud sl user permission-edit $id --permission "VPN_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "VULN_SCAN_MANAGE"  

    ibmcloud sl user permission-edit $id --permission "ACCESS_ALL_GUEST"  	
    ibmcloud sl user permission-edit $id --permission "ACCESS_ALL_HARDWARE"  

    ibmcloud sl user permission-edit $id --permission "TICKET_ADD"  
    ibmcloud sl user permission-edit $id --permission "TICKET_EDIT"  
    ibmcloud sl user permission-edit $id --permission "TICKET_MANAGE"  
    ibmcloud sl user permission-edit $id --permission "TICKET_SEARCH"  
    ibmcloud sl user permission-edit $id --permission "TICKET_VIEW"  
    ibmcloud sl user permission-edit $id --permission "TICKET_VIEW_ALL"  
    ibmcloud sl user permission-edit $id --permission "TICKET_VIEW_BY_HARDWARE"  
    ibmcloud sl user permission-edit $id --permission "TICKET_VIEW_BY_VIRTUAL_GUEST" 
    ;;

  *)
    echo "No se encontró ningun grupo de acceso"
    ;;
  esac
  wait
  echo "Permisos actualizados"
fi

exit 0
